language: python
python:
- '2.7'
install: pip install requests
deploy:
  provider: s3
  access_key_id: AKIAJA3MR3WBOADKEKRQ
  secret_access_key:
    secure: "wT3gbwAeT5Y3H/fQbzgAld/HwtyyX0P5+0OcTsanpGKOdIeo1k1xbnCKFx0z1PMNpwJlY1RUyNCOLezFmn/8qAPwgXW4zKdfKAhOrsuojqv+tMnlqnoSUOYl2U8TlXoOHbcvH9bSuEW6hKxE5mnLlAYK1EqApWii6PHBOK6YQK4="
  bucket: s3.johanwiren.se
  region: eu-west-1
  endpoint: s3.johanwiren.se.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: dist
  upload-dir: packages/johanwiren/PlaysafeWorker
script: python setup.py sdist
