language: python
python:
- '2.7'
install: pip install requests
deploy:
  provider: s3
  access_key_id: AKIAJFMAQS24LL3P7HAQ
  secret_access_key:
    secure: "AUJU0pv7nqOpBEfkQdXg9UpXDqtTfKw1Vozwxe9oeN1IkjkwM0d0Nkn5FvfNPe3sf6L/qkUi0xsbM9ztCVzhcxoQBCd7Fy8k/+dqTUwKbu3oOD6lYrSOrFPOYe9bDzvE095rUpbl5G5NiOu+bGx0a1BPSMx9KldTcwrwkyEujIo="
  bucket: s3.johanwiren.se
  region: eu-west-1
  endpoint: s3.johanwiren.se.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: dist
  upload-dir: packages/johanwiren/PlaysafeWorker
script: python setup.py sdist
