language: python
python:
- '2.7'
install: pip install requests
deploy:
  provider: s3
  access_key_id: AKIAJFMAQS24LL3P7HAQ
  secret_access_key:
    secure: AXkJRkLsT2GaCJF9fVMtgSeRnk32UX/7NN2WpZDl7e8gRERHyQvjMS/eWhkGErl4SFHYhtFzkEhwIDi4YUgQrIF6i2h7V4qb68rcZtLfRbM8DThecboy4g1pOZ1YydDC8mgGlON0vImX4fy9TOZYLI6ku67+BUnR11FELW8sOn8=
  bucket: s3.johanwiren.se
  region: eu-west-1
  endpoint: s3.johanwiren.se.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: dist
  upload-dir: packages/johanwiren/PlaysafeWorker
script: python setup.py sdist
